contact_links:
  - name: ğŸ™Œ Contribution Guide
    url: https://github.com/test
    about: Please read through before making contributions.
  - name: ğŸ’¬ test's Discord Server
    url: https://test.test/
    about: Want to discuss / chat with the community? Here you go!
  - name: â‰ï¸ Why and How to make a reproduction?
    url: https://testtest.test
    about: Reproduction is very important for maintainer to help on your issues!
